import { Inter } from 'next/font/google';
import { AuthProvider } from '../components/auth/AuthProvider';
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';
import Head from 'next/head';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Mshopping',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <Head>
          <style>
            {`body { font-family: ${inter.style.fontFamily}; }`}
          </style>
        </Head>
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
